### ISSUE TITLE
Trying to integrate with zigbee2mqtt

### ISSUE THREAD

**Issue by Koenkk** [HalleyAssist/zigbee-shepherd#2]
Hey HalleyAssist!

I'm trying to integrate this zigbee-shepherd fork into zigbee2mqtt. Flashed my CC2531 with Z-stack 3.0.1 ZNP firmware.

package.json
```js
    "zcl-packet": "https://github.com/HalleyAssist/zcl-packet.git",
    "zigbee-shepherd": "git+https://github.com/HalleyAssist/zigbee-shepherd.git#f3c602944e551da6756bda2ce98586830c3c57a8",
```

However when starting I get the following error:
```js
  zigbee-shepherd:request REQ --> ZDO:nodeDescReq +1ms
  cc-znp:SREQ --> ZDO:nodeDescReq, { dstaddr: 0, nwkaddrofinterest: 0 } +0ms
  @serialport/stream _write 9 bytes of data +1ms
  @serialport/binding-abstract write 9 bytes +1ms
  zigbee-shepherd:init Coordinator initialize had an error: TypeError: controller.limitConcurrency(...) is not a function
    at Object.querie.device (/Users/Koenkk/Git/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/querie.js:70:6)
    at Object.querie.deviceWithEndpoints (/Users/Koenkk/Git/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/querie.js:106:19)
    at Controller.simpleDescReq (/Users/Koenkk/Git/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/controller.js:471:24)
    at Object.init._registerDelegators (/Users/Koenkk/Git/zigbee2mqtt/node_modules/zigbee-shepherd/lib/initializers/init_controller.js:76:23)
    at /Users/Koenkk/Git/zigbee2mqtt/node_modules/zigbee-shepherd/lib/initializers/init_controller.js:21:21
    at _fulfilled (/Users/Koenkk/Git/zigbee2mqtt/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/Koenkk/Git/zigbee2mqtt/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/Koenkk/Git/zigbee2mqtt/node_modules/q/q.js:816:13)
    at /Users/Koenkk/Git/zigbee2mqtt/node_modules/q/q.js:624:44
    at runSingle (/Users/Koenkk/Git/zigbee2mqtt/node_modules/q/q.js:137:13) +0ms
```

Is this a known problem or am I doing something wrong?

**Comment by splitice** [comment]
Not sure as to the cause.

`controller.limitConcurrency` is just a hook point for anyone who wants to add rate limiting etc. The default implementation (noop) just returns the first argument (fn) and calls it.

Please note our fork has a higher minimum nodejs requirement (we run NodeJS 9.x but  6+ should be fine).

Looking over the code briefly I can't see your problem unfortunately. The code looks fine. Perhaps try debugging?

**Comment by splitice** [comment]
Nevermind I see the issue! Fixing.

**Comment by Koenkk** [comment]
Great, will test again and let you know!
